name: electric_cli
description: A Very Good Project created by Very Good CLI.
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  archive: ^3.3.7
  args: ^2.4.1
  cli_completion: ^0.3.0
  electric_client: ^0.1.0
  http: ^1.1.0
  mason_logger: ^0.2.5
  path: ^1.8.3

dev_dependencies:
  build_runner: ^2.4.4
  build_verify: ^3.1.0
  build_version: ^2.1.1
  mocktail: ^0.3.0
  test: ^1.24.2
  very_good_analysis: ^5.0.0

dependency_overrides:
  electric_client:
    path: ..

executables:
  electric_cli:
