include: package:lint/strict.yaml

analyzer:
      
  language:
    strict-casts: true
    strict-inference: true

  errors:
    non_constant_identifier_names: ignore
    todo: info

linter:
  rules:
    prefer_single_quotes: true
    unawaited_futures: true
    unrelated_type_equality_checks: true
    avoid_print: true

    # Deactivate some rules
    avoid_classes_with_only_static_members: false
    use_setters_to_change_properties: false
    avoid_redundant_argument_values: false
    no_leading_underscores_for_local_identifiers: false
