name: electric_client
description: A Dart implementation for Electric (electric-sql.com).
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.4 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lint: ^2.0.1
  test: ^1.24.1
  
dependencies:
  collection: ^1.17.1
  equatable: ^2.0.5
  events_emitter: ^0.5.2
  fixnum: ^1.1.0
  fpdart: ^0.5.0
  http: ^0.13.5
  meta: ^1.9.1
  protobuf: ^2.1.0
  retry: ^3.1.1
  sqlite3: ^1.10.1
  synchronized: ^3.0.1
  uuid: ^3.0.7
  web_socket_channel: ^2.3.0
  # web_socket_client: ^0.1.0-dev.3
