name: electric_client
description: A Dart implementation for Electric (electric-sql.com).
version: 0.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.0.0 <4.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lint: ^2.0.1
  test: ^1.24.1
  
dependencies:
  collection: ^1.17.0
  crypto: ^3.0.3
  dart_jsonwebtoken: ^2.8.2
  drift: ^2.9.0
  equatable: ^2.0.5
  events_emitter: ^0.5.2
  fixnum: ^1.1.0
  fpdart: ^0.6.0
  http: ^1.1.0
  logging: ^1.1.1
  meta: ^1.8.0
  protobuf: ^3.0.0
  rate_limiter: ^1.0.0
  retry: ^3.1.1
  sqlite3: ^2.0.0
  synchronized: ^3.0.1
  uuid: ^3.0.7
  web_socket_channel: ^2.3.0
  # web_socket_client: ^0.1.0-dev.3

dependency_overrides:
  sqlite3:
    git:
      url: https://github.com/davidmartos96/sqlite3.dart
      path: sqlite3
      ref: 8adca89b9bdbea9f880fe8092c409b173ca4f036