import 'package:code_builder/code_builder.dart';

abstract class ElectricDriftGenOpts {
  /// Customize the way the Drift table name class is generated
  /// null means use the default
  String? resolveTableName(String sqlTableName) {
    return null;
  }

  /// Customize the way the Drift column name class is generated
  /// null means use the default
  String? resolveColumnName(String sqlTableName, String sqlColumnName) {
    return null;
  }

  /// Customize the way the Drift data class is generated
  DataClassNameInfo? resolveDataClassName(String sqlTableName) {
    return null;
  }
}

/// Options to customize how the [DataClassName] from drift annotation is generated
class DataClassNameInfo {
  /// The name of the data class
  final String name;

  /// The [code_builder] [Reference] to the parent type of the data class generated by drift.
  /// For example: `refer('BaseModel', 'package:myapp/base_model.dart')`
  final Reference? extending;

  DataClassNameInfo(
    this.name, {
    this.extending,
  });
}
