name: electricsql
description: A Dart implementation for Electric (electric-sql.com).
version: 0.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.0.0 <4.0.0'
  
dependencies:
  collection: ^1.0.0
  crypto: ^3.0.0
  dart_jsonwebtoken: ^2.8.2
  drift: ^2.0.0
  equatable: ^2.0.0
  events_emitter: ^0.5.2
  fixnum: ^1.0.0
  fpdart: ^1.0.0
  http: ^1.0.0
  logging: ^1.0.0
  meta: ^1.0.0
  protobuf: ^3.0.0
  rate_limiter: ^1.0.0
  retry: ^3.0.0
  sqlite3: ^2.1.0
  synchronized: ^3.0.0
  uuid: ^3.0.0
  web_socket_channel: ^2.0.0

dev_dependencies:
  lint: ^2.1.2
  test: ^1.24.4