name: electricsql
description: A Dart implementation for ElectricSQL (electric-sql.com) client.
version: 0.5.0+1
repository: https://github.com/SkillDevs/electric_dart

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  ansicolor: ^2.0.1
  collection: ^1.0.0
  crypto: ^3.0.0
  dart_jsonwebtoken: ^2.8.2
  drift: ^2.15.0
  equatable: ^2.0.0
  events_emitter: ^0.5.2
  fixnum: ^1.0.0
  http: ^1.0.0
  logging: ^1.0.0
  meta: ^1.0.0
  platform_info: ^4.0.2
  postgres: ^3.0.8
  protobuf: ^3.0.0
  rate_limiter: ^1.0.0
  retry: ^3.0.0
  sqlite3: ^2.2.0
  synchronized: ^3.0.0
  uuid: ^4.0.0
  web_socket_channel: ^2.3.0

dev_dependencies:
  build_runner: ^2.4.6
  drift_dev: ^2.15.0
  fast_immutable_collections: ^9.1.5
  file: ^7.0.0 # Lowest version supported
  lint: ^2.3.0
  pub_semver: ^2.1.4 # Lowest version supported
  test: ^1.24.6
  watcher: ^1.1.0 # Lowest version supported
