name: todos_electrified
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'


dependencies:
  flutter:
    sdk: flutter

  electric_client:
    path: ../

  cupertino_icons: ^1.0.2
  sqlite3: ^2.0.0
  path: ^1.8.2
  hooks_riverpod: ^2.3.5
  path_provider: ^2.0.14
  logging: ^1.2.0
  drift: ^2.9.0

  
  flutter_hooks: ^0.18.6
  uuid: ^3.0.7
  
    

dev_dependencies:
  drift_dev: ^2.8.2
  build_runner: ^2.4.4
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

