name: todos_electrified
description: A todos ElectricSQL application.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  animated_emoji: ^2.0.0
  cupertino_icons: ^1.0.2
  drift: ^2.14.0
  electricsql:
    path: ../packages/electricsql
  electricsql_flutter:
    path: ../packages/electricsql_flutter
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.1
  flutter_svg: ^2.0.7
  hooks_riverpod: ^2.3.10
  intl: ^0.18.1
  logging: ^1.2.0
  material_design_icons_flutter: ^7.0.7296
  material_symbols_icons: ^4.2668.0
  path: ^1.8.2
  path_provider: ^2.0.14
  sqlite3: ^2.1.0
  # Pinned, because the web requires an extra file per version
  # https://github.com/simolus3/sqlite3.dart/releases?q=sqlite3_flutter_libs&expanded=true
  sqlite3_flutter_libs: 0.5.18

dev_dependencies:
  build_runner: ^2.4.4
  drift_dev: ^2.14.0
  electricsql_cli:
    path: ../packages/electricsql_cli

  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - packages/animated_emoji/lottie/electricity.json
    - assets/electric.svg
