name: todos_electrified
description: A todos ElectricSQL application.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  animated_emoji: ^3.0.0
  cupertino_icons: ^1.0.2
  drift: 2.18.0 # Pinned version because we bundle drift_worker.js, which is different depending on the version
  electricsql:
    path: ../packages/electricsql
  electricsql_flutter:
    path: ../packages/electricsql_flutter
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.1
  flutter_svg: ^2.0.7
  hooks_riverpod: ^2.3.10
  intl: ^0.19.0
  logging: ^1.2.0
  material_design_icons_flutter: ^7.0.7296
  material_symbols_icons: ^4.2741.0
  path: ^1.8.2
  path_provider: ^2.1.1
  sqlite3: ^2.4.3
  # Pinned, because the web requires an extra file per version
  # https://github.com/simolus3/sqlite3.dart/releases?q=sqlite3_flutter_libs&expanded=true
  sqlite3_flutter_libs: 0.5.22

  # THese are only used for the backend example, they are not needed to use Electric
  # in Flutter apps.
  postgres: ^3.0.8
  drift_postgres: ^1.2.3
  shelf: ^1.4.1
  shelf_router: ^1.1.4

dev_dependencies:
  build_runner: ^2.4.4
  drift_dev: 2.18.0
  electricsql_cli:
    path: ../packages/electricsql_cli
  file: ^7.0.0 # Lowest version supported

  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

  platform: ^3.1.3 # Lowest version supported
  pub_semver: ^2.1.4 # Lowest version supported
  watcher: ^1.1.0 # Lowest version supported

flutter:
  uses-material-design: true

  assets:
    - packages/animated_emoji/lottie/electricity.json
    - assets/electric.svg
