name: todos_electrified
description: A todos ElectricSQL application.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  electricsql_flutter:
    path: ../packages/electricsql_flutter
  electricsql:
    path: ../packages/electricsql
  cupertino_icons: ^1.0.2
  sqlite3: ^2.1.0
  sqlite3_flutter_libs: ^0.5.17
  path: ^1.8.2
  hooks_riverpod: ^2.3.10
  path_provider: ^2.0.14
  logging: ^1.2.0
  drift: ^2.10.0
  animated_emoji: ^2.0.0
  material_design_icons_flutter: ^7.0.7296
  flutter_hooks: ^0.20.1
  material_symbols_icons: ^4.2668.0
  flutter_svg: ^2.0.7

dev_dependencies:
  drift_dev: ^2.8.2
  build_runner: ^2.4.4
  electricsql_cli:
    path: ../packages/electricsql_cli
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - packages/animated_emoji/lottie/electricity.json
    - assets/electric.svg
