name: electricsql_cli
description: CLI to interact with the ElectricSQL service. Offers a similar tool
  set as the NPM electric_sql package.
repository: https://github.com/SkillDevs/electric_dart
version: 0.4.1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  archive: ^3.3.7
  args: ^2.4.1
  code_builder: ^4.8.0
  dart_style: ^2.3.2
  dotenv: ^4.2.0
  electricsql: ^0.4.0
  http: ^1.1.0
  mason_logger: ^0.2.5
  package_config: ^2.1.0
  path: ^1.8.3
  recase: ^4.1.0
  web_socket_channel: ^2.3.0

dev_dependencies:
  build_runner: ^2.4.7
  build_verify: ^3.1.0
  build_version: ^2.1.1
  file: ^7.0.0 # Lowest version supported
  lint: ^2.1.2
  mocktail: ^1.0.1
  pub_semver: ^2.1.4 # Lowest version supported
  test: ^1.24.2
  watcher: ^1.1.0 # Lowest version supported

executables:
  electricsql_cli:
