name: electricsql_cli
description: CLI to interact with the ElectricSQL service. Offers a similar tool
  set as the NPM electric_sql package.
repository: https://github.com/SkillDevs/electric_dart
version: 0.4.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  archive: ^3.3.7
  args: ^2.4.1
  code_builder: ^4.5.0
  dart_style: ^2.3.0
  electricsql: ^0.4.0
  http: ^1.1.0
  mason_logger: ^0.2.5
  path: ^1.8.3
  recase: ^4.1.0

dev_dependencies:
  build_runner: ^2.4.4
  build_verify: ^3.1.0
  build_version: ^2.1.1
  lint: ^2.1.2
  mocktail: ^1.0.1
  test: ^1.24.2

executables:
  electricsql_cli:
