name: electricsql_flutter
description: Flutter specific utilities for the electricsql Dart package. Can be
  used as a standalone package instead of electricsql.
repository: https://github.com/SkillDevs/electric_dart
version: 0.7.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  electricsql: ^0.7.0

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^2.3.0
