name: satellite_dart_client
description: A sample command-line application.
version: 1.0.0
publish_to: 'none'
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  collection: ^1.18.0
  drift: ^2.17.0
  # drift_postgres: ^1.2.1
  drift_postgres: 
    git:
      url: https://github.com/simolus3/drift
      path: extras/drift_postgres
      ref: 6ba049e5df7f2a3aff50c02ffdd326f596f53452
  electricsql: any
  electricsql_cli: any
  postgres: ^3.1.0

dependency_overrides:
  electricsql:
    path: ../../packages/electricsql
  electricsql_cli:
    path: ../../packages/electricsql_cli

dev_dependencies:
  build_runner: ^2.4.6
  drift_dev: ^2.17.0
  lints: ^2.1.1
  path: ^1.8.3
  test: ^1.21.0
