name: satellite_dart_client
description: A sample command-line application.
version: 1.0.0
publish_to: 'none'
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  drift: ^2.13.0
  electricsql:
    path: ../../packages/electricsql

dev_dependencies:
  build_runner: ^2.4.6
  drift_dev: ^2.13.0
  lints: ^2.0.0
  test: ^1.21.0
