name: satellite_dart_client
description: A sample command-line application.
version: 1.0.0
publish_to: 'none'
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  drift: ^2.14.0
  electricsql: any
  electricsql_cli: any

dependency_overrides:
  electricsql:
    path: ../../packages/electricsql
  electricsql_cli:
    path: ../../packages/electricsql_cli

dev_dependencies:
  build_runner: ^2.4.6
  drift_dev: ^2.14.0
  lints: ^2.1.1
  path: ^1.8.3
  test: ^1.21.0
