name: electricsql_devtools_extension
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  auto_size_text: ^3.0.0
  data_table_2: ^2.5.12
  devtools_app_shared: ^0.1.1
  devtools_extensions: ^0.1.1
  electricsql: ^0.7.0
  flutter:
    sdk: flutter
  flutter_portal: ^1.1.4
  flutter_riverpod: ^2.5.1
  syntax_highlight: ^0.4.0
  vm_service: ^14.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^2.3.0

dependency_overrides:
  web: ^0.5.0

flutter:

  uses-material-design: true
