name: Tests (Lowest constraints)

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install Melos
        run: dart pub global activate melos

      - name: Boostrap
        run: melos bs

      - name: Downgrade deps
        run: melos deps_downgrade

      - name: Run tests
        run: melos test:all

  analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install Melos
        run: dart pub global activate melos

      - name: Boostrap
        run: melos bs

      - name: Downgrade deps
        run: melos deps_downgrade

      - name: Analyze project source
        run: melos analyze