name: Tests (Lowest constraints)

on:
  push:
    branches:
      - master
      - develop
      - feat/*
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install Melos
        run: dart pub global activate melos

      - name: Boostrap
        run: melos bs

      - name: Downgrade deps
        run: melos run deps_downgrade

      # pre-pull the image so `usePostgresDocker` does not delay which may causes 
      # tests to timeout
      - name: pull latest postgres image
        run: docker pull postgres:latest

      - name: Run tests
        run: melos run test:all

  analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install Melos
        run: dart pub global activate melos

      - name: Boostrap
        run: melos bs

      - name: Downgrade deps
        run: melos run deps_downgrade

      - name: Analyze project source
        run: melos run analyze